[package]
name = "hexi-lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "big_file_dump"
harness = false
