[package]
name = "hexi"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexi-lib = { path = "../hexi-lib" }
clap = { version = "2.33", features = ["yaml"] }
libc = "0.2"